name: DevBox-v0
services:
  server:
    image: meayush/devploy-server:v1.0.1
    restart: always
    env_file: ./server/.env
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - devbox-network
    command: sh -c "npx prisma migrate deploy && npm run start"


  client:
    image: meayush/devploy-client:v2.8.0
    restart: always
    env_file: ./client/.env
    environment:
      - NODE_ENV=production
    networks:
      - devbox-network
    # command: npm run dev -- --host
    depends_on:
      - server

  worker:
    image: meayush/devploy-worker:v1.1.0
    restart: always
    env_file: ./server/.env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - devbox-network
    depends_on:
      - server
    command: ["npm", "run", "start:cron"]
  
  
  caddy:
    image: meayush/devploy-caddy:v2.2.0
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - devbox-network
    depends_on:
      - server
      - client

volumes:
  caddy_data:
  caddy_config:

networks:
  devbox-network:
    driver: bridge
